#!/usr/bin/env python3
"""Build search-index.js — the site-wide search index used by the header search.

Runs automatically from .githooks/pre-commit on every commit, so a new page is
searchable as soon as it is committed. Manual run:  python3 tools/search/build_index.py

Source of truth = the pages themselves (no hand-maintained text):
  - <title>              (site suffix stripped)
  - <meta description>   (truncated)
  - JSON-LD name / alternateName / creator.name  (e.g. Hebrew + English artist names)
Page type = first path segment (artists → דף אומן, works → יצירה, ...). Unknown
sections fall back to "עמוד", so a brand-new section is still indexed.

Only git-tracked/staged pages are indexed (not the raw working tree), so a
half-written page from a parallel session never ships in the index.
Output is deterministic (sorted, no timestamp) to avoid no-op diffs.
"""
import html, json, os, re, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'search-index.js')
SKIP = ('_staging/', 'trash/', '_originals/', 'node_modules/', 'scratchpad/',
        'lighthouse-reports/', 'newsletter-backend/', 'tools/', 'docs/', 'components/')
TYPE_ORDER = ['artists', 'exhibitions', 'events', 'galleries', 'curators',
              'sponsors', 'opencalls', 'press', 'page', 'works']
DESC_MAX = 120

SUFFIX = re.compile(r'\s*[—|\-–]\s*Zielinski\s*&\s*Rozen(\s+Art\s+Galleries)?\s*$', re.I)
SLUG = re.compile(r'^[a-z0-9]+(-[a-z0-9]+)+$')
EXTRA_SUFFIX =re.compile(r'\s*—\s*(Exhibition|Event|Press)\s*$', re.I)


def tracked_pages():
    out = subprocess.run(['git', 'ls-files', '--cached', '-z', '--', '*index.html', 'index.html'],
                         cwd=ROOT, capture_output=True, check=True).stdout.decode('utf-8')
    paths = sorted({p for p in out.split('\0') if p.endswith('index.html')})
    return [p for p in paths if not p.startswith(SKIP) and os.path.exists(os.path.join(ROOT, p))]


def clean(s):
    return re.sub(r'\s+', ' ', html.unescape(s or '')).strip()


def ld_names(src):
    names = []
    for block in re.findall(r'<script type="application/ld\+json"[^>]*>(.*?)</script>', src, re.S):
        try:
            data = json.loads(block)
        except ValueError:
            continue
        nodes = data.get('@graph', [data]) if isinstance(data, dict) else data
        for n in nodes if isinstance(nodes, list) else []:
            if not isinstance(n, dict) or n.get('@type') in ('BreadcrumbList', 'WebSite', 'Organization'):
                continue
            for key in ('name', 'alternateName'):
                v = n.get(key)
                for x in (v if isinstance(v, list) else [v]):
                    if isinstance(x, str):
                        names.append(clean(SUFFIX.sub('', x)))
            c = n.get('creator')
            if isinstance(c, dict) and isinstance(c.get('name'), str):
                names.append(clean(c['name']))
    return names


def entry(path):
    src = open(os.path.join(ROOT, path), encoding='utf-8').read()
    if re.search(r'<meta[^>]+name="robots"[^>]+noindex', src, re.I):
        return None
    url = path[:-len('index.html')]
    seg = url.split('/')[0] if url else ''
    kind = seg if seg in TYPE_ORDER else 'page'
    m = re.search(r'<title>(.*?)</title>', src, re.S)
    title = clean(m.group(1)) if m else ''
    short = EXTRA_SUFFIX.sub('', SUFFIX.sub('', title)).strip()
    title = short or title
    m = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', src)
    desc = clean(m.group(1)) if m else ''
    if len(desc) > DESC_MAX:
        desc = desc[:DESC_MAX].rsplit(' ', 1)[0] + '…'
    low = title.lower()
    keys = []
    for n in ld_names(src):
        head = re.split(r'\s+[—|]\s+', n)[0].lower()
        if (not n or SLUG.match(n) or head in low or n in keys
                or re.fullmatch(r'zielinski\s*&\s*rozen', n, re.I)):
            continue
        keys.append(n)
    rec = {'u': url, 't': kind, 'n': title}
    if keys:
        rec['k'] = ' · '.join(keys)
    if desc:
        rec['d'] = desc
    return rec


def main():
    items = [e for e in (entry(p) for p in tracked_pages()) if e]
    items.sort(key=lambda e: (TYPE_ORDER.index(e['t']), e['u']))
    body = json.dumps(items, ensure_ascii=False, separators=(',', ':'))
    js = ('/* AUTO-GENERATED by tools/search/build_index.py (pre-commit hook). Do not edit. */\n'
          'window.__SEARCH_INDEX__=' + body + ';\n')
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else None
    if old != js:
        open(OUT, 'w', encoding='utf-8').write(js)
    if '-q' not in sys.argv:
        print('search-index.js: %d pages, %d bytes%s' % (len(items), len(js.encode()), '' if old != js else ' (unchanged)'))


if __name__ == '__main__':
    main()
