#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Regenerate every GENERATED data copy from data/*.json (the single source of truth).

Why copies exist at all: pages opened as file:// cannot fetch() JSON, so any page
that must render from data locally carries (or loads) a copy. This script owns all
copies that are an exact function of the JSON. Hand-curated mirrors are NOT touched —
they are listed in docs/data-contracts.md ("Mirror registry") with their source.

Generated targets:
  data/generated/artists.js        ← data/artists.json                 (window.__ARTISTS_INLINE__)
  data/generated/art-works.js      ← data/works.json  art_works         (window.__ART_WORKS_INLINE__)
  data/generated/ex-statements.js  ← data/works.json  exhibition_statements (window.__EX_STATEMENTS_INLINE__)
  data/generated/ex-order.js       ← data/exhibitions.json slug order   (window.__EX_ORDER_INLINE__)
      ↑ loaded by every artists/<slug>/index.html via <script src="../../data/generated/…">
  works/index.html            #works-data         ← art_works
  works/<id>/index.html       #artwork-data       ← that art_works record (+ statement fallback, below)
  galleries/<slug>/index.html #g-artworks-data    ← art_works where gallery_slug == <slug> (field projection)
  galleries/*/, curators/korin-avraham/ #fallback-galleries ← data/galleries.json

Usage (repo root or anywhere):
  python3 tools/sync_data.py          # write everything that is stale
  python3 tools/sync_data.py --check  # write nothing; exit 1 and list what is stale

Run it after ANY change to artists.json / works.json / exhibitions.json / galleries.json.
Idempotent: a second run changes nothing. Every file it lists as updated belongs in the SAME
commit as the JSON change (the pages carry inline-only copies — leaving one out ships a stale site).
"""
import json, re, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECK = "--check" in sys.argv[1:]
stale = []      # human-readable list of targets that differ from what the JSON implies
written = []


def rel(p):
    return os.path.relpath(p, ROOT)


def load(name):
    with open(os.path.join(ROOT, "data", name), encoding="utf-8") as f:
        return json.load(f)


def emit(path, new_text):
    """Write path if its content differs (or record it as stale in --check mode)."""
    full = os.path.join(ROOT, path)
    old = open(full, encoding="utf-8").read() if os.path.exists(full) else None
    if old == new_text:
        return
    stale.append(path)
    if not CHECK:
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(new_text)
        written.append(path)


def compact(v):
    return json.dumps(v, separators=(",", ":"), ensure_ascii=False)


# ---------------------------------------------------------------- sources
ARTISTS = load("artists.json")
WORKS = load("works.json")
ART = WORKS["art_works"]
STORE = WORKS["exhibition_statements"]
BY_ID = {w["id"]: w for w in ART}
# data/exhibitions.json is ordered chronologically ASCENDING; artist pages sort their
# exhibition groups by this index DESCENDING (newest show on top — user decision 2026-08-12).
EX_ORDER = [e["slug"] for e in load("exhibitions.json")["exhibitions"]]
GALLERIES = load("galleries.json")

HEADER = ("/* GENERATED by tools/sync_data.py from {src} — do not edit by hand.\n"
          "   Edit the JSON, then run: python3 tools/sync_data.py */\n")

GENERATED = [
    # (file, global, value, source description)
    ("data/generated/artists.js", "__ARTISTS_INLINE__", ARTISTS, "data/artists.json"),
    ("data/generated/art-works.js", "__ART_WORKS_INLINE__", ART, "data/works.json (art_works)"),
    ("data/generated/ex-statements.js", "__EX_STATEMENTS_INLINE__", STORE, "data/works.json (exhibition_statements)"),
    ("data/generated/ex-order.js", "__EX_ORDER_INLINE__", EX_ORDER, "data/exhibitions.json (slug order)"),
]


def gen_scripts():
    for path, var, value, src in GENERATED:
        emit(path, HEADER.format(src=src) + "window.%s=%s;\n" % (var, compact(value)))


# ------------------------------------------------ artist pages: plumbing guard
# Every artist page must load the generated files and must NOT carry an inline copy
# (an old-style inline copy would silently shadow nothing but go stale — and it is
# exactly what older instructions told agents to paste). Which scripts a page loads is
# part of its template: the 3 legacy-renderer pages (alon, dan-ben-ary,
# zohar-ron-dan-ben-ari) never had ex-statements/ex-order.
INLINE_RE = re.compile(r'<script id="(artists-inline|art-works-inline|ex-statements-inline|ex-order-inline)">')
SRC_RE = re.compile(r'<script src="\.\./\.\./data/generated/([a-z-]+)\.js"></script>')


def check_artist_pages():
    problems = []
    for fp in sorted(glob.glob(os.path.join(ROOT, "artists", "*", "index.html"))):
        t = open(fp, encoding="utf-8").read()
        inl = INLINE_RE.findall(t)
        if inl:
            problems.append("%s: inline data copy %s — replace with data/generated/*.js" % (rel(fp), inl))
        srcs = set(SRC_RE.findall(t))
        need = {"artists", "art-works"}
        if "function buildExGroups(list){" in t:
            need |= {"ex-statements", "ex-order"}
        missing = need - srcs
        if missing:
            problems.append("%s: missing <script src> for data/generated/%s.js" % (rel(fp), sorted(missing)))
    return problems


# ------------------------------------------------ works grid + single artwork pages
def sync_works_grid():
    fp = "works/index.html"
    t = open(os.path.join(ROOT, fp), encoding="utf-8").read()
    pretty = "\n" + json.dumps(ART, ensure_ascii=False, indent=2) + "\n"
    t2, n = re.subn(r'(<script[^>]*id="works-data"[^>]*>).*?(</script>)',
                    lambda m: m.group(1) + pretty + m.group(2), t, count=1, flags=re.S)
    if not n:
        print("  ! #works-data not found in", fp, file=sys.stderr)
    emit(fp, t2)


def sync_artwork_pages():
    # statement_he shown on a single artwork page = the work's own text if any, ELSE the
    # artist's exhibition statement from the store, ELSE nothing.
    store_lut = {(r["artist_slug"], r["exhibition_title_he"]): r["statement_he"] for r in STORE}
    for fp in sorted(glob.glob(os.path.join(ROOT, "works", "*", "index.html"))):
        t = open(fp, encoding="utf-8").read()
        m = re.search(r'(<script[^>]*id="artwork-data"[^>]*>)(\{.*?\})(</script>)', t, re.S)
        if not m:
            continue
        wid = json.loads(m.group(2)).get("id")
        base = BY_ID.get(wid)
        if not base:
            print("  ! artwork page id not in works.json:", wid, rel(fp), file=sys.stderr)
            continue
        rec = dict(base)
        if not rec.get("statement_he"):
            stmt = store_lut.get((rec["artist_slug"], rec.get("exhibition_title_he")))
            if stmt:
                rec["statement_he"] = stmt
            else:
                rec.pop("statement_he", None)
        emit(rel(fp), t[:m.start(2)] + compact(rec) + t[m.end(2):])


# ------------------------------------------------ gallery pages
G_ARTWORK_FIELDS = ["id", "artist_slug", "artist_en", "artist_he", "title_en", "title_he",
                    "img", "w", "h", "widths"]


def sync_gallery_pages():
    for fp in sorted(glob.glob(os.path.join(ROOT, "galleries", "*", "index.html"))):
        slug = os.path.basename(os.path.dirname(fp))
        t = open(fp, encoding="utf-8").read()
        m = re.search(r'(<script[^>]*id="g-artworks-data"[^>]*>)(.*?)(</script>)', t, re.S)
        if m:
            # keep the page's own field set/order (read from its first record) so the
            # projection stays exactly what the carousel renderer expects
            cur = json.loads(m.group(2))
            fields = list(cur[0].keys()) if cur else G_ARTWORK_FIELDS
            proj = [{k: w.get(k) for k in fields} for w in ART
                    if w.get("gallery_slug") == slug and not w.get("hidden")]
            t = t[:m.start(2)] + "\n" + json.dumps(proj, ensure_ascii=False, indent=2) + "\n" + t[m.end(2):]
        emit(rel(fp), t)


def sync_fallback_galleries():
    pages = sorted(glob.glob(os.path.join(ROOT, "galleries", "*", "index.html"))) + \
        [os.path.join(ROOT, "curators", "korin-avraham", "index.html")]
    for fp in pages:
        if not os.path.exists(fp):
            continue
        t = open(fp, encoding="utf-8").read()
        m = re.search(r'(<script[^>]*id="fallback-galleries"[^>]*>)(.*?)(</script>)', t, re.S)
        if not m:
            continue
        emit(rel(fp), t[:m.start(2)] + compact(GALLERIES) + t[m.end(2):])


def main():
    gen_scripts()
    sync_works_grid()
    sync_artwork_pages()
    sync_gallery_pages()
    sync_fallback_galleries()
    problems = check_artist_pages()
    for p in problems:
        print("  ! " + p, file=sys.stderr)
    if CHECK:
        if stale or problems:
            for s in stale:
                print("  stale: " + s)
            print("sync_data --check: %d stale target(s), %d artist-page problem(s). "
                  "Run: python3 tools/sync_data.py" % (len(stale), len(problems)))
            sys.exit(1)
        print("sync_data --check: all generated data is up to date.")
        return
    print("sync_data: %d file(s) updated%s" % (len(written), ":" if written else "."))
    for w in written:          # the FULL list — every one of these must go into the same commit
        print("  " + w)
    if problems:
        sys.exit(1)


if __name__ == "__main__":
    main()
